package vc.list.common;
/**
 * 娑堟伅绫诲瀷鍒嗕负涓夌被锛氬懡浠MD---鏁版嵁DAT---缁撴灉RST
 * @author Aodong Shen
 *
 */
public interface MessageType {
	//--------Command---------//
	String CMD_LOGIN = "CMD_LOGIN";
	String CMD_LOGOUT = "CMD_LOGOUT";
	String CMD_REGISTER = "CMD_REGISTER";
	
	String CMD_QUERY_STUDENTNAME ="CMD_QUERY_STUDENTNAME";
	String CMD_QUERY_STUDENTID = "CMD_QUERY_STUDENTID";
	String CMD_QUERY_STUDENTNUM = "CMD_QUERY_STUDENTNUM";
	String CMD_QUERY_STUDENTDEPARTMENT = "CMD_QUERY_STUDENTDEPARTMENT";
	String CMD_QUERY_STUDENTMAJOR = "CMD_QUERY_STUDENTMAJOR";
	String CMD_QUERY_STUDENTGRADE = "CMD_QUERY_STUDENTGRADE";
	String CMD_GETALLSTUDENT = "CMD_GETALLSTUDENT";
	String CMD_INSERT_STUDENT = "CMD_INSERT_STUDENT";
	String CMD_DELETE_STUDENT = "CMD_DELETE_STUDENT";
	String CMD_UPDATE_STUDENTNAME = "CMD_UPDATE_STUDENTNAME";
	String CMD_UPDATE_STUDENTNUM = "CMD_UPDATE_STUDENTNUM";
	String CMD_UPDATE_STUDENTGRADE = "CMD_UPDATE_STUDENTGRADE";
	String CMD_UPDATE_STUDENTDEPARTMENT = "CMD_UPDATE_STUDENTDEPARTMENT";
	String CMD_UPDATE_STUDENTMAJOR = "CMD_UPDATE_STUDENTMAJOR";
	String CMD_UPDATE_STUDENTCLASS = "CMD_UPDATE_STUDENTCLASS";
	String CMD_UPDATE_STUDENTLENGTH = "CMD_UPDATE_STUDENTLENGTH";
	String CMD_UPDATE_STUDENTRE = "CMD_UPDATE_STUDENTRE";
	String CMD_UPDATE_STUDENTINSCHOOL = "CMD_UPDATE_STUDENTINSCHOOL";
	
    String CMD_CHECK_GOODS = "CMD_CHECK_GOODS";
    String CMD_OPEN_GOODS_MAIN = "CMD_OPEN_GOODS_MAIN";
    String CMD_QUERY_GOODS = "CMD_QUERY_GOODS";
    String CMD_CHECK_ACCOUNT = "CMD_CHECK_ACCOUNT";
    String CMD_ADD_GOODS = "CMD_ADD_GOODS";
    String CMD_DEPOSIT = "CMD_DEPOSIT";
    String CMD_DELETE_GOODS = "CMD_DELETE_GOODS";
    
    
    String CMD_CHECK_BOOK = "CMD_CHECK_BOOK";//鏌ヨ鍊熼槄璁板綍
    String CMD_QUERY_BOOKID = "CMD_QUERY_BOOKID";
    String CMD_QUERY_BOOKNAME = "CMD_QUERY_BOOKNAME";
    String CMD_QUERY_BOOKWRITER = "CMD_QUERY_BOOKWRITER";
    String CMD_QUERY_SEAT = "CMD_QUERY_SEAT";
    String CMD_ADD_BOOK = "CMD_ADD_BOOK";
    String CMD_DELETE_BOOK = "CMD_DELETE_BOOK";
    String CMD_CHECK_ALLBOOK = "CMD_CHECK_ALLBOOK";//锟斤拷询锟斤拷锟斤拷锟介籍
    String CMD_NOTFIND_BOOK = "CMD_NOTFIND_BOOK";
    //--------Data------------//
	String DAT_LOGOUT = "DAT_LOGOUT";
	String DAT_LOGIN = "DAT_LOGIN";
	
	String DAT_TEXT = "DAT_TEXT";//鏅�氫俊鎭寘
	String DAT_ACTION = "DAT_ACTION"; // 鍔ㄤ綔鍖�
	

	
	String DAT_ADD_FRIEND = "DAT_ADD_FRIEND";
	String DAT_DEL_FRIEND = "DAT_DEL_FRIEND";
	String DAT_UPD_FRIEND = "DAT_UPD_FRIEND";
	String DAT_QUY_FRIEND = "DAT_QUY_FRIEND";
	
	//--------Result----------//
	String RST_SUCCESS = "Success";//琛ㄦ槑鏄惁鎴愬姛
	String RST_FAILURE = "Failure";//琛ㄦ槑澶辫触	

	
}
