package vc.list.common;
/**
 * 消息类型分为三类：命令CMD---数据DAT---结果RST
 * @author Aodong Shen
 *
 */
public interface MessageType {
	//--------Command---------//
	String CMD_LOGIN = "CMD_LOGIN";
	String CMD_LOGOUT = "CMD_LOGOUT";
	String CMD_REGISTER = "CMD_REGISTER";
	String CMD_CHANGE_PASSWORD = "CMD_CHANGE_PASSWORD";
	String CMD_CHANGE_PASSWORDFAILED = "CMD_CHANGE_PASSWORDFAILED";
	String CMD_QUERY_STUDENTNAME ="CMD_QUERY_STUDENTNAME";
	String CMD_QUERY_STUDENTID = "CMD_QUERY_STUDENTID";
	String CMD_QUERY_STUDENTNUM = "CMD_QUERY_STUDENTNUM";
	String CMD_QUERY_STUDENTDEPARTMENT = "CMD_QUERY_STUDENTDEPARTMENT";
	String CMD_QUERY_STUDENTMAJOR = "CMD_QUERY_STUDENTMAJOR";
	String CMD_QUERY_STUDENTGRADE = "CMD_QUERY_STUDENTGRADE";
	String CMD_GETALLSTUDENT = "CMD_GETALLSTUDENT";
	String CMD_INSERT_STUDENT = "CMD_INSERT_STUDENT";
	String CMD_DELETE_STUDENT = "CMD_DELETE_STUDENT";
	String CMD_UPDATE_STUDENTNAME = "CMD_UPDATE_STUDENTNAME";
	String CMD_UPDATE_STUDENTNUM = "CMD_UPDATE_STUDENTNUM";
	String CMD_UPDATE_STUDENTGRADE = "CMD_UPDATE_STUDENTGRADE";
	String CMD_UPDATE_STUDENTDEPARTMENT = "CMD_UPDATE_STUDENTDEPARTMENT";
	String CMD_UPDATE_STUDENTMAJOR = "CMD_UPDATE_STUDENTMAJOR";
	String CMD_UPDATE_STUDENTCLASS = "CMD_UPDATE_STUDENTCLASS";
	String CMD_UPDATE_STUDENTLENGTH = "CMD_UPDATE_STUDENTLENGTH";
	String CMD_UPDATE_STUDENTRE = "CMD_UPDATE_STUDENTRE";
	String CMD_UPDATE_STUDENTINSCHOOL = "CMD_UPDATE_STUDENTINSCHOOL";
	
    String CMD_CHECK_GOODS = "CMD_CHECK_GOODS";
    String CMD_OPEN_GOODS_MAIN = "CMD_OPEN_GOODS_MAIN";
    String CMD_QUERY_GOODS = "CMD_QUERY_GOODS";
    String CMD_CHECK_ACCOUNT = "CMD_CHECK_ACCOUNT";
    String CMD_ADD_GOODS = "CMD_ADD_GOODS";
    String CMD_DEPOSIT = "CMD_DEPOSIT";
    String CMD_DELETE_GOODS = "CMD_DELETE_GOODS";
    String CMD_SCAN_GOODS = "CMD_SCAN_GOODS";
    String CMD_DEDUCT = "CMD_DEDUCT";
    
    String CMD_QUERY_COURSEID = "CMD_QUERY_COURSEID";
    String CMD_ADD_COURSE = "CMD_ADD_COURSE";
    String CMD_CHOOSE_COURSE = "CMD_CHOOSE_COURSE";
    String CMD_QUIT_COURSE = "CMD_QUIT_COURSE";
    String CMD_DELETE_COURSE = "CMD_DELETE_COURSE";
    String CMD_SHOW_COURSE = "CMD_SHOW_COURSE";
    String CMD_SHOWSTUDENT_COURSE="CMD_SHOWSTUDENT_COURSE";
    String CMD_SHOWTEACHER_COURSE="CMD_SHOWTEACHER_COURSE";
    
    String CMD_CHECK_BOOK = "CMD_CHECK_BOOK";//查询借阅记录
    String CMD_QUERY_BOOKID = "CMD_QUERY_BOOKID";
    String CMD_QUERY_BOOKNAME = "CMD_QUERY_BOOKNAME";
    String CMD_QUERY_BOOKWRITER = "CMD_QUERY_BOOKWRITER";
    String CMD_QUERY_SEAT = "CMD_QUERY_SEAT";
    String CMD_ADD_BOOK = "CMD_ADD_BOOK";
    String CMD_DELETE_BOOK = "CMD_DELETE_BOOK";
    String CMD_CHECK_ALLBOOK = "CMD_CHECK_ALLBOOK";//��ѯ�����鼮
    String CMD_NOTFIND_BOOK = "CMD_NOTFIND_BOOK";
    //--------Data------------//
	String DAT_LOGOUT = "DAT_LOGOUT";
	String DAT_LOGIN = "DAT_LOGIN";
	
	String DAT_TEXT = "DAT_TEXT";//普通信息包
	String DAT_ACTION = "DAT_ACTION"; // 动作包
	

	
	String DAT_ADD_FRIEND = "DAT_ADD_FRIEND";
	String DAT_DEL_FRIEND = "DAT_DEL_FRIEND";
	String DAT_UPD_FRIEND = "DAT_UPD_FRIEND";
	String DAT_QUY_FRIEND = "DAT_QUY_FRIEND";
	
	//--------Result----------//
	String RST_SUCCESS = "Success";//表明是否成功
	String RST_FAILURE = "Failure";//表明失败	

	
}
